### ISSUE TITLE
*zoom should be zoom

### ISSUE THREAD

**Issue by CosmicWebServices** [JarvusInnovations/emergence-skeleton-v2#10]
```
/* line 17, ../sass/skeleton/_utilities.scss */
.clearfix {
  *zoom: 1;
}
```
Found in slate site-root/css/main.css

**Comment by themightychris** [comment]
@CosmicWebServices this is an IE6/7 compatibility hack and is intentional http://nicolasgallagher.com/micro-clearfix-hack/
