### ISSUE TITLE
Site-Admin/Precache - all options unchecked by default

### ISSUE THREAD

**Issue by mijogu** [JarvusInnovations/emergence-skeleton-v2#6]
Whenever I need to precache files it's only in one mayyybe two folders. Seems like it'd be better to have all options on the /site-admin/precache page unchecked by default so you can save a few clicks.

**Comment by themightychris** [comment]
@mijogu totally agree, fixed in 39afee9ae94e5c6bcbeffbd6f84bfd1bb958ce1f 

I also added a text field for typing in an arbitrary path and a "select all" button
